name: CI

on:
  push:
    tags:
      - "*.*.*-*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        run: |
          pip install PyGithub tomli-w
      - name: Generate
        run: |
          python3 genFrcutilReleases.py > frcutil_releases.toml
      - name: Commit
        run: |
          git config user.email "132951735+frc4533-lincoln@users.noreply.github.com"
          git config user.name "frc4533-lincoln"
          git add *
          git commit -m 'actions: Auto-update'
          git push
