name: CI

on:
  push:
    tags:
      - "*.*.*-*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate extract list
        run: |
          chmod +x $GITHUB_WORKSPACE/genExtractList.sh && \
          $GITHUB_WORKSPACE/genExtractList.sh
      - name: Package dist tarballs
        run: |
          chmod +x $GITHUB_WORKSPACE/package.sh && \
          $GITHUB_WORKSPACE/package.sh
      - name: Upload tarballs to Github releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/wpilib-novsc-*.tar.xz
