name: CI

on:
  push:
    tags:
      - "*.*.*-*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        run: |
          pip install PyGithub tomli-w
      - name: Generate
        run: |
          python3 genFrcutilReleases.py > $GITHUB_WORKSPACE/frcutil_releases.toml
      - name: Commit
        run: |
          git add *
          git commit -m 'Update frcutil releases'
          git push
